version: '3.9'
services:
  postgres:
    container_name: postgresql
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trae
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trae"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    name: agent_pgdata
    external: true
