openapi: 3.0.0
info:
  title: Document Editor API
  version: 1.0.0
paths:
  /documents:
    get:
      summary: List all documents
      responses:
        '200':
          description: Document list
          content:
            application/json:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
    post:
      summary: Create new document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Document created
          content:
            application/json:
              properties:
                id:
                  type: string
  /documents/{id}:
    get:
      summary: Get document content
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Document content
          content:
            application/json:
              properties:
                content:
                  type: string
    put:
      summary: Update document content
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Document updated
    delete:
      summary: Delete document
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Document deleted
  /documents/{id}/search-replace:
    post:
      summary: Search and replace text
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                old_str:
                  type: string
                new_str:
                  type: string
      responses:
        '200':
          description: Text replaced
          content:
            application/json:
              properties:
                replaced_count:
                  type: integer